import os
print("\033[1;92m [•] 𝗦𝗨𝗝𝗢𝗬 CYBER (ROBOT) SYSTEM INSTALL. . . . \033[1;30m")
os.system("pkg install espeak")
os.system("git pull")
print("\033[1;92m   [•] ROBOT INSTALL COMPLETE \033[1;30m")
os.system('espeak -a 300 "Robot install complete"')
print("\033[1;92m   [•] UPDATE CHECKING \033[1;30m")
os.system('espeak -a 300 "WAITING FOR UPDATE"')
os.system('espeak -a 300 "Facebook id  Sujoy "')
print("Facebook id rj sujoy raj")
os.system('espeak -a 300 "bd sujoy yt"')
print("'\033[31;1m' -https://www.facebook.com/profile.php?id=100088012276367&mibextid=ZbWKwL") 
os.system('espeak -a 300 "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"')
print("bangla benson borno")
os.system('espeak -a 300 "assalamualaikum Im sujoy cyber"')
print(" [•] WELLCOME SAHADAT")
os.system('espeak -a 300 "WELLCOME SAHADAT"')
os.system('espea -a 300 "sahadat madarchod bainchod tore paiya loi"')
os.system('espeak -a 300 " sashadat maderchod sashadat maderchod sashadat maderchod sashadat maderchod sashadat maderchod sashadat maderchod sashadat maderchod sashadat maderchod sashadat maderchod sashadat maderchod"') 